# do not put this file into dir with chinese name, unless you specify "container_name" for each container
version: "3.9"
services:
  node01:           
    # container_name: node01
    image: cantjie/pytorch:1.13.1
    volumes:
      - .:/workspace      # <host(local) dir (should start with . or /)>:<dir in container>
    command:              # python /workspace/model.py --n_devices=1 --rank=0 --gpu=0
      - python
      - -u
      - /workspace/model.py 
      - --n_devices=3
      - --rank=0
      # - --gpu=0
      - --master_addr=localhost
      - --master_port=12355

  node02:           
    image: cantjie/pytorch:1.13.1
    volumes:
      - .:/workspace  
    command: 
      - python
      - -u
      - /workspace/model.py 
      - --n_devices=3
      - --rank=1
      # - --gpu=0
      - --master_addr=node01  # docker compose automatically adds the hosts: 'node01' -> node01's ip 
      - --master_port=12355
    depends_on:
      - node01

  node03:           
    image: cantjie/pytorch:1.13.1
    volumes:
      - .:/workspace  
    command: 
      - python
      - -u
      - /workspace/model.py 
      - --n_devices=3
      - --rank=2
      # - --gpu=0
      - --master_addr=node01 
      - --master_port=12355
    depends_on:
      - node01
    